### ISSUE TITLE
Getting Errno 121: remote I/O error

### ISSUE THREAD

**Issue by pkoprov** [Intelligent-Vehicle-Perception/MPU-9250-Sensors-Data-Collect#15]
I installed the library without smbus2 at first and it was running fake smbus correctly. After I installed smbus2 the example code stopped working. it gives an error 121. what should I do?

**Comment by JAAdrian** [comment]
+1  
I have exactly the same issue. Can't really tell what's going wrong here.

**Comment by pkoprov** [comment]
I found out that I bought a fake sensor. A friend of mine gave me one that he used in his RC car a while ago and it works now. I think that Amazon sells some crappy stuff.

**Comment by jdc-cunningham** [comment]
Yeah sucks about the hit/miss of sensor quality.
Especially when they're not really cheap at $14 ea.

**Comment by JafetSalgado** [comment]
I have exactly the same issue
![Screenshot 2022-11-13 014536](https://user-images.githubusercontent.com/112973143/201511248-99cf6fdb-01e1-45af-a7ad-2e03f9126e26.jpg)
![Screenshot 2022-11-13 014555](https://user-images.githubusercontent.com/112973143/201511249-3482da3f-15c8-4ddf-9672-8fce20033465.jpg)

**Comment by campagnani** [comment]
@JafetSalgado the magnetometer address is 0x0C and don't appaers in the image of terminal you send here.

Maybe you burn it pluggin the sensor in 5v?

I did the same thing (plug the MPU9250 in 5v) and burn just the IC of magnetometer.
