### ISSUE TITLE
master-only-mode.py  uses address_mpu_master=MPU9050_ADDRESS_69  

### ISSUE THREAD

**Issue by nvtkaszpir** [Intelligent-Vehicle-Perception/MPU-9250-Sensors-Data-Collect#3]
Is it on purpose that file `master-only-mode.py` uses `address_mpu_master=MPU9050_ADDRESS_69`?
shouldn't it be `address_mpu_master=MPU9050_ADDRESS_68` because AFAIR 0x68 is used by default.

**Comment by jefmenegazzo** [comment]
The address 0x69 was used arbitrarily, since both 0x68 and 0x69 work. Since the default is 0x68, code and documentation were changed in the new version 1.0.10.
