### ISSUE TITLE
No data on RPI.

### ISSUE THREAD

**Issue by oziqus** [Intelligent-Vehicle-Perception/MPU-9250-Sensors-Data-Collect#5]
Using Fake SMBus 
 Install requirements. 

|.....MPU9250 in 0x68 Address.....|
Accelerometer [0.0, 0.0, 0.0]
Gyroscope [0.0, 0.0, 0.0]
Magnetometer [0.0, 0.0, 0.0]
Temperature 21.0

mpu is connected correctly.

**Comment by jefmenegazzo** [comment]
@oziqus The project libraries are not installed. So, instead of using the real bus with your MPU, the fake bus is being used.

You can install the dependencies using the command:

`pip install -r requirements.txt `
